---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - yum: name={{ item }} state=present
      with_items:
        - etcd
        - kubernetes

    - copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - src: apiserver
          dest: /etc/kubernetes/apiserver
        - src: docker
          dest: /etc/sysconfig/docker
        - src: kubelet
          dest: /etc/kubernetes/kubelet
        - src: daemon.json
          dest: /etc/docker/daemon.json

    - name: remove some weird files
      file: path=/etc/docker/certs.d state=absent

    - service: name={{ item }} state=started enabled=yes
      with_items:
        - etcd
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
        - kube-proxy
        - kubelet
