apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: ${token}
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: ${host_ip}
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
clusterName: kubernetes
kubernetesVersion: v1.13.2
controlPlaneEndpoint: ${api_endpoint}:6443
apiServer:
  certSANs:
  - "${api_endpoint}"
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: "172.20.0.0/16"
etcd:
  local:
    serverCertSANs:
    - ${host_name}
    - ${host_ip}
    peerCertSANs:
    - ${host_name}
    - ${host_ip}
    extraArgs:
      name: "${host_name}"
      listen-client-urls: "https://127.0.0.1:2379,https://${host_ip}:2379"
      advertise-client-urls: https://${host_ip}:2379
      listen-peer-urls: https://${host_ip}:2380
      initial-advertise-peer-urls: https://${host_ip}:2380
      initial-cluster: "${etcd_cluster}"
      ##### notice this setting !!
      initial-cluster-state: ${state} #new or existing
