# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.ssh.insert_key = false
  # config.vm.synced_folder '.', '/vagrant', type: 'nfs'

  # VirtualBox.
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.box = "centos7"
    server.vm.box_url = "builds/virtualbox-centos7.box"
    server.vm.network :private_network, ip: "172.16.3.2"

    config.vm.provider :virtualbox do |vb_cfg|
      # vb_cfg.name = "centos7-server"
      vb_cfg.memory = 1024
      vb_cfg.cpus = 2
      # vb_cfg.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      # vb_cfg.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    # config.vm.provision "shell", inline: "echo Hello, World"
  end
end
